mysql:
  build: .
  dockerfile: Dockerfile-MySQL
  environment:
    MYSQL_ROOT_PASSWORD: password        #rootユーザ用のパスワード
    MYSQL_USER: user                     #作業ユーザ名
    MYSQL_PASSWORD: pass     #作業ユーザ用のパスワード
    MYSQL_DATABASE: introduction    #作成するDB名
    TZ: "Asia/Tokyo"
  ports:
    - 3306:3306
  volumes:
    - ./db:/var/lib/mysql